version: '3'

services:
  web:
    container_name: ${SITE}-wordpress-web
    build:
      context: .
      dockerfile: etc/docker/web/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    ports:
      - "8831:80"
    env_file: .env
    links:
      - app
    volumes:
      - .:/var/www/html
    networks:
      - default
  app:
    container_name: ${SITE}-wordpress-app
    build:
      context: .
      dockerfile: etc/docker/app/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
        SITE: ${SITE}
        WORDPRESS_VERSION: ${WORDPRESS_VERSION}
        WOOCOMMERCE_VERSION: ${WOOCOMMERCE_VERSION}
        PAYDESIGN_VERSION: ${PAYDESIGN_VERSION}
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    env_file: .env
    networks:
      - default
  db:
    container_name: ${SITE}-wordpress-db
    build:
      context: .
      dockerfile: etc/docker/db/Dockerfile
    restart: always
    volumes:
      - ./etc/docker/db/data:/var/lib/mysql
    ports:
      - "33311:3306"
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file: .env
    networks:
      - default

